### ISSUE TITLE
Mavericks compatibility

### ISSUE THREAD

**Issue by ZetaKebab** [nikkimoreaux/Jumpcut#1]
Hello,

It seems your Retina version of Jumpcut does not compile on Mavericks.
![image 2014-06-03 a 15 39 44](https://cloud.githubusercontent.com/assets/1267647/3160778/ec0fecae-eb24-11e3-93eb-b31c034f4078.png)

**Comment by nikkimoreaux** [comment]
Hi Théo, you live in Nancy right?

Moi aussi ! Alors je vais m'exprimer en français. Si tu le souhaites tu peux télécharger une version compilée à cette adresse : http://diplodoc.us/stuffs/Jumpcut.app.zip

Je pense voir au cours de la beta de Yosemite si Jumpcut y fonctionne toujours. Si besoin je m'occuperais de ces petits bugs. Car là tout de suite je n'ai pas trop le temps de m'occuper des depreciations d'un si petit projet. 

Bonne journée.

**Comment by ZetaKebab** [comment]
Ah, c'est super ça :) Merci beaucoup, ça fait une icône pixelisée de moins dans ma barre des menus.
Merci beaucoup !

**Comment by nikkimoreaux** [comment]
⚠️ Since Steve Cook has re-updated his code, I'm not updating this app anymore ; please find the original (and now more recent) release here: https://snark.github.io/jumpcut/
