### ISSUE TITLE
Add Yosemite dark menu bar art 

### ISSUE THREAD

**Issue by bcomnes** [nikkimoreaux/Jumpcut#2]
Would you be willing to add the light menu bar icon artwork for use with the dark menu bar in OS X 10.10?  

Thanks for the fork!

**Comment by nikkimoreaux** [comment]
I take note. Maybe next week.

**Comment by bcomnes** [comment]
No rush.  Thank you!

**Comment by bcomnes** [comment]
A work around i found was to just use the unicode scissors options.  Dark menu art for the actual logo would be great, but I'm going to close this issue for now.
