### ISSUE TITLE
Cannot update to 0.70

### ISSUE THREAD

**Issue by vronizor** [nikkimoreaux/Jumpcut#3]
Hi,

I get an error when trying to update to version 0.70 (see screenshot). Tried rebooting, reinstalling 0.63, no success. I'm running Mojave 10.14.6 on a MacBook Pro 13-inch, 2016.

Thanks for taking up the development of this great tool.

Best

<img width="678" alt="image" src="https://user-images.githubusercontent.com/22742874/64684324-d10f8800-d47c-11e9-86f5-c43eaf88eb4b.png">

<img width="532" alt="Screen Shot 2019-09-11 at 10 09 43" src="https://user-images.githubusercontent.com/22742874/64684272-b63d1380-d47c-11e9-8e01-644c9c704907.png">

**Comment by nikkimoreaux** [comment]
⚠️ Since Steve Cook has re-updated his code, I'm not updating this app anymore ; please find the original (and now more recent) release here: https://snark.github.io/jumpcut/
