### ISSUE TITLE
jumpcut crashes when I change to 'hiragana' (Japanese) keyboard input source 

### ISSUE THREAD

**Issue by MarinosK** [nikkimoreaux/Jumpcut#4]
I have three input sources installed in my keyboard, English, Greek and Japanese (Hiragana). Whenever I switch from English to Greek and vice versa all is OK. Whenever I switch to Hiragana Jumpcut crashes without any warning. I'm using Jumpcut 0,71. Note that with 0,63 and the exactly same setup everything was normal.

**Comment by nikkimoreaux** [comment]
⚠️ Since Steve Cook has re-updated his code, I'm not updating this app anymore ; please find the original (and now more recent) release here: https://snark.github.io/jumpcut/
